### PR TITLE
Support back to API 10

### PR DESCRIPTION
**Pull request by pserwylo**
This PR adds support for Android back to Gingerbread (API 10).

The only thing seemingly stopping this was the use of animations. This change addresses it in two ways:

 * Using `ViewCompat` where necessary.
 * Directly setting properties (e.g. padding) instead of animating them.
 * Using `setVisibility(View.GONE)` instead of `setScaleX(0)`/`setScaleY(0)` when on Gingerbread.
 * Changing text size instead of the scale of the `TextView` when on Gingerbread.

Note that although `ViewCompat` provides a `setScaleX()` and y method, these literally do nothing, and are only there so the compiler doesn't complain. As such I've opted not to make use of them, because it was hiding when I really needed to use `setVisibility()` instead of `setScaleX(0)`.

The only thing I can't seem to get working is the way the `CoordinatorLayout` shows/hides the bottom nav on Gingerbread. It hides it correctly if I scroll down, but doesn't show it again when scrolling up.

Is anybody able to provide any feedback on whether this is a problem with the sample application, or with the library itself?

### CODE REVIEW

**Comment by pserwylo** [comment]
If this is something you'd be happy to merge, then let me know if you'd like me to squash my commits.

**Comment by pserwylo** [comment]
Hmm, not quite sure what is going on with this CI failure. `./gradlew build connectedCheck` seems to work on my devbox, and I'm unsure of the difference with this Travis instance. Any thoughts?

**Comment by Ashok-Varma** [comment]
CI i need to fix even for the main branch it's not working. But supporting till API 10 we are sacrificing things yet gaining very little advantage so mostly this pull will not be merged.

As you can see that below 1% people are from 10-14 => https://developer.android.com/about/dashboards/index.html

**Comment by pserwylo** [comment]
Okay, sorry to hear you feel that way. I tried very hard to make it so that nothing is sacrificed (from the users perspective, there is a small increase in technical debt for the library contributors). The feature set should be exactly the same for users on API 14 as if this change was note merged.

**Pull request closed without merging**
