### PR TITLE
Migrate to AndroidX

### PR DESCRIPTION
**Pull request by tuuzed**

### CODE REVIEW

**Comment by Ashok-Varma** [comment]
#207 
Reverted this on many users request

**Comment by mochadwi** [comment]
any milestone to reverted back to AndroidX?

**Comment by mochadwi** [comment]
@Ashok-Varma

**Comment by Ashok-Varma** [comment]
Hi @mochadwi, right now development of library is paused [in favour of google release bottom-nav](https://developer.android.com/reference/com/google/android/material/bottomnavigation/BottomNavigationView)

May be we should release a new version with androidX (to support devs who are updating). Will check back later this weekend, feel free to submit a pull-request.

**Pull request merged**
